### PR TITLE
Generic Service Recycle Workflow

### PR DESCRIPTION
**Pull request by prabhat250980**
This workflow is able to restart service for both os Linux as well as windows

### CODE REVIEW

**Comment by prabhat250980** [comment]
Hi ,

I have couple doubt here so in my workflow I have used some PowerShell
script  and that script is on my local server .

In the workflow i have just give the path of that script so my question is
while exporting workflow and sharing it on github how i can share that
powershell script file.

can you please share detail about that.


Thanks

**Comment by JackyLey** [comment]
Hi,

You can upload the script as well under the same folder and then in the readme file describe what the folder contains (workflow, script, etc.) and how everything can be used by someone else (importing process).

Thanks,

[cid:04f52f50-6635-4b6b-a69a-3d803155471e]www.ayehu.com<http://www.ayehu.com/>

Jacky Leybman, Technical Product Manager

Ayehu Inc. 1441 Broadway, 6 Floor,  New York, NY 10018

Mobile: 480-242-2143 | Office: 1-646-518-7915

Jacky@ayehu.com<mailto:Jacky@ayehu.com> | Join 'IT Automation Experts' group<https://www.linkedin.com/groups/4140672/>



This email and any files transmitted with it are restricted and intended solely for the use of the individual or entity to whom they are addressed

________________________________

**Comment by prabhat250980** [comment]
ok thanks for guiding through this

**Comment by JackyLey** [comment]
Kumar,

I see that you've created a pull request - you should be able to merge it to the master by yourself since you've been added as a collaborator already

A couple of additional comments:
1. The main folder should have spaces 'Generic Service Recycle'

2. The readme file needs to README.md (instead if README.txt)

3. The readme file needs to contain more information and be better structured, please see an example here:
https://github.com/Ayehu/custom-workflows/tree/master/Low%20Disk%20Space%20Remediation


Thanks,

[cid:75ccea0d-59be-4e48-a960-a9cbe85e137e]www.ayehu.com<http://www.ayehu.com/>

Jacky Leybman, Technical Product Manager

Ayehu Inc. 1441 Broadway, 6 Floor,  New York, NY 10018

Mobile: 480-242-2143 | Office: 1-646-518-7915

Jacky@ayehu.com<mailto:Jacky@ayehu.com> | Join 'IT Automation Experts' group<https://www.linkedin.com/groups/4140672/>



This email and any files transmitted with it are restricted and intended solely for the use of the individual or entity to whom they are addressed

________________________________

**Pull request merged**
